package com.tencent.tinker.internal.deploy.legacy.dex

import com.tencent.tinker.Tinker
import com.tencent.tinker.internal.TEST_ASSETS_DIRECTORY_NAME
import com.tencent.tinker.internal.TEST_DEX_FILE_NAME
import com.tencent.tinker.internal.legacy.commons.dexpatcher.DexPatchApplier
import com.tencent.tinker.internal.util.HashOutputStream
import com.tencent.tinker.internal.util.asMd5HashNullable
import com.tencent.tinker.internal.util.asMd5String
import com.tencent.tinker.internal.util.async
import com.tencent.tinker.internal.util.classesDexWithIndexPattern
import com.tencent.tinker.internal.util.copyAndGenerateHash
import com.tencent.tinker.internal.util.crc32
import com.tencent.tinker.internal.util.debugLog
import com.tencent.tinker.internal.util.ensureParentIsExistingDirectory
import com.tencent.tinker.internal.util.expected
import com.tencent.tinker.internal.util.searchAndSortDexFiles
import com.tencent.tinker.internal.util.traceE
import com.tencent.tinker.internal.util.traceS
import com.tencent.tinker.internal.util.withTemporaryDirectory
import com.tencent.tinker.internal.ziputil.AlignedZipOutputStream
import java.io.File
import java.util.zip.ZipEntry
import java.util.zip.ZipFile

private const val TAG = "Tinker.Deploy.Legacy.Dex"

private class DexMetadata(
    /**
     * Name of dex file.
     */
    val name: String,

    /**
     * MD5 hash of patched file.
     */
    val patchedHash: ByteArray?,

    /**
     * MD5 hash of diff file.
     *
     * Entry in diff package is a diff file. The patched file is generated by combining base file and diff file.
     */
    val diffHash: ByteArray?,

    /**
     * CRC32 checksum of base file.
     */
    val baseCrc32: Long,
) {
    override fun toString(): String = buildList {
        add("dex_metadata {")
        add("  name: $name")
        add("  patched_hash: ${patchedHash?.asMd5String}")
        add("  diff_hash: ${diffHash?.asMd5String}")
        add("  base_crc32: ${baseCrc32.toString(16)}")
        add("}")
    }.joinToString("\n")
}

private val ByteArray.parsedDexMetadataList: List<DexMetadata>
    get() = toString(Charsets.UTF_8)
        .split("\n")
        .filter { it.isNotBlank() }
        .mapIndexedNotNull { lineNumberMinusOne, line ->
            val parts = line.split(",")
            if (parts.size < 8) {
                throw Tinker.Error(
                    Tinker.Error.Deploy.Legacy.Dex.INVALID_METADATA,
                    "Line ${lineNumberMinusOne + 1} only has ${parts.size} parts.",
                )
            }
            val name = parts[0].trim()
            if (name == "test.dex") {
                // Ignores test dex file in legacy diff package, use new verification strategy.
                return@mapIndexedNotNull null
            }
            val mode = parts[7].trim()
            if (mode != "raw") {
                throw Tinker.Error(
                    Tinker.Error.Deploy.Legacy.Dex.UNSUPPORTED_DEX_MODE,
                    "Mode \"$mode\" for dex \"$name\" is unsupported.",
                )
            }
            val patchedHash = try {
                parts[3].trim().asMd5HashNullable
            } catch (throwable: Throwable) {
                throw Tinker.Error(
                    Tinker.Error.Deploy.Legacy.Dex.INVALID_METADATA,
                    "Patched hash of line ${lineNumberMinusOne + 1} is invalid.",
                    throwable,
                )
            }
            val diffHash = try {
                parts[4].trim().asMd5HashNullable
            } catch (throwable: Throwable) {
                throw Tinker.Error(
                    Tinker.Error.Deploy.Legacy.Dex.INVALID_METADATA,
                    "Diff hash of line ${lineNumberMinusOne + 1} is invalid.",
                    throwable,
                )
            }
            val baseCrc32 = try {
                parts[5].trim().toLong()
            } catch (throwable: Throwable) {
                throw Tinker.Error(
                    Tinker.Error.Deploy.Legacy.Dex.INVALID_METADATA,
                    "Base file CRC32 of line ${lineNumberMinusOne + 1} is invalid.",
                    throwable,
                )
            }
            return@mapIndexedNotNull DexMetadata(
                name = name,
                patchedHash = patchedHash,
                diffHash = diffHash,
                baseCrc32 = baseCrc32,
            )
        }

/**
 * Creates newly added dex file from diff package. The content of newly added dex file is same as diff file.
 *
 * Returns the MD5 hash of created dex file.
 */
private fun File.createDexAsNewlyAdded(
    metadata: DexMetadata,
    diffPackage: ZipFile,
): ByteArray {
    val output = resolve(metadata.name)
    debugLog(TAG) {
        "Creating dex file \"${metadata.name}\" as newly added to \"${output.absolutePath}\"."
    }
    val entry = diffPackage.getEntry(metadata.name)
        ?: throw Tinker.Error(
            Tinker.Error.Deploy.Legacy.Dex.MISSING_DIFF_ENTRY,
            "Cannot find entry \"${metadata.name}\" in diff package \"${diffPackage.name}\"."
        )
    return diffPackage.getInputStream(entry)
        .use { stream ->
            output.ensureParentIsExistingDirectory()
                .outputStream()
                .buffered()
                .use(stream::copyAndGenerateHash)
        }
}

/**
 * Copies not-modified dex file from base apk file. The content of created dex file is same as original dex file in base
 * apk file.
 *
 * Returns the MD5 hash of created dex file.
 */
private fun File.createDexAsNotModified(
    metadata: DexMetadata,
    baseApk: ZipFile,
): ByteArray {
    val output = resolve(metadata.name)
    debugLog(TAG) {
        "Creating dex file \"${metadata.name}\" as not-modified to \"${output.absolutePath}\"."
    }
    val entry = baseApk.getEntry(metadata.name)
        ?: throw Tinker.Error(
            Tinker.Error.Deploy.Legacy.Dex.MISSING_BASE_ENTRY,
            "Cannot find entry \"${metadata.name}\" in base apk file \"${baseApk.name}\"."
        )
    if (entry.crc != metadata.baseCrc32) {
        throw Tinker.Error(
            Tinker.Error.Deploy.Legacy.Dex.INVALID_BASE_ENTRY,
            "CRC32 checksum \"${entry.crc}\" of entry \"${metadata.name}\" in base apk file "
                    + "\"${baseApk.name}\" is not match \"${metadata.baseCrc32}\" in metadata.",
        )
    }
    return baseApk.getInputStream(entry)
        .use { stream ->
            output.ensureParentIsExistingDirectory()
                .outputStream()
                .buffered()
                .use(stream::copyAndGenerateHash)
        }
}

/**
 * Creates dex file by merging base dex file and diff file.
 *
 * Returns the MD5 hash of created dex file.
 */
private fun File.createDexByMerging(
    metadata: DexMetadata,
    baseApk: ZipFile,
    diffPackage: ZipFile,
): ByteArray {
    val outputFile = resolve(metadata.name)
    debugLog(TAG) {
        "Creating dex file \"${metadata.name}\" by merging to \"${outputFile.absolutePath}\"."
    }
    val baseEntry = baseApk.getEntry(metadata.name)
        ?: throw Tinker.Error(
            Tinker.Error.Deploy.Legacy.Dex.MISSING_BASE_ENTRY,
            "Cannot find entry \"${metadata.name}\" in base apk file \"${baseApk.name}\"."
        )
    if (baseEntry.crc != metadata.baseCrc32) {
        throw Tinker.Error(
            Tinker.Error.Deploy.Legacy.Dex.INVALID_BASE_ENTRY,
            "CRC32 checksum \"${baseEntry.crc}\" of entry \"${metadata.name}\" in base apk file "
                    + "\"${baseApk.name}\" is not match \"${metadata.baseCrc32}\" in metadata.",
        )
    }
    val diffEntry = diffPackage.getEntry(metadata.name)
        ?: throw Tinker.Error(
            Tinker.Error.Deploy.Legacy.Dex.MISSING_DIFF_ENTRY,
            "Cannot find entry \"${metadata.name}\" in diff package \"${diffPackage.name}\"."
        )
    return outputFile
        .ensureParentIsExistingDirectory()
        .outputStream()
        .buffered()
        .use { output ->
            HashOutputStream(output)
                .also { wrapped ->
                    baseApk.getInputStream(baseEntry).use { baseInput ->
                        diffPackage.getInputStream(diffEntry).use { diffInput ->
                            DexPatchApplier(baseInput, diffInput)
                                .executeAndSaveTo(wrapped)
                        }
                    }
                }
                .digest
        }
}

/**
 * Creates dex files and save to [extractedDirectory].
 */
private fun createDexFiles(
    baseApk: ZipFile,
    diffPackage: ZipFile,
    extractedDirectory: File,
) {
    val metadataFile = diffPackage.getEntry("assets/dex_meta.txt")
        ?: throw Tinker.Error(
            Tinker.Error.Deploy.Legacy.Dex.MISSING_METADATA,
            "Cannot find dex metadata in diff package ${diffPackage.name}."
        )
    val metadataList = traceE("deploy.legacy.dex.read_metadata") {
        diffPackage.getInputStream(metadataFile)
            .use {
                it.readBytes()
            }
            .parsedDexMetadataList
    }
    debugLog(TAG) {
        buildList {
            add("Read dex metadata from ${diffPackage.name}:")
            addAll(metadataList)
        }.joinToString("\n")
    }
    async {
        metadataList.forEach { metadata ->
            launch {
                val hash = if (metadata.baseCrc32 == 0L) {
                    // No base dex file, the patched dex file is newly added.
                    traceE("deploy.legacy.dex.create(name = ${metadata.name}, strategy = newly_added)") {
                        extractedDirectory.createDexAsNewlyAdded(metadata, diffPackage)
                    }
                } else if (metadata.diffHash == null) {
                    // No diff file, the patched dex file is not modified.
                    traceE("deploy.legacy.dex.create(name = ${metadata.name}, strategy = not_modified)") {
                        extractedDirectory.createDexAsNotModified(metadata, baseApk)
                    }
                } else {
                    traceE("deploy.legacy.dex.create(name = ${metadata.name}, strategy = merging)") {
                        extractedDirectory.createDexByMerging(metadata, baseApk, diffPackage)
                    }
                }
                if (!hash.contentEquals(metadata.patchedHash)) {
                    throw Tinker.Error(
                        Tinker.Error.Deploy.Legacy.Dex.INVALID_DEPLOY_RESULT,
                        "Hash \"${hash.asMd5String}\" of patch result \"${metadata.name}\" "
                                + "is not match \"${metadata.patchedHash?.asMd5String}\" in metadata.",
                    )
                }
            }
        }
        launch {
            traceS("deploy.legacy.dex.create_test") {
                val output = extractedDirectory.resolve(TEST_DEX_FILE_NAME)
                debugLog(TAG) {
                    "Creating test dex file to \"${output.absolutePath}\"."
                }
                // Since we need to get checksum by reading base apk, we just read test dex file from it instead of assets
                // API.
                val testDexEntry = baseApk.getEntry("assets/${TEST_ASSETS_DIRECTORY_NAME}/${TEST_DEX_FILE_NAME}") ?: throw Tinker.Error(
                    Tinker.Error.Deploy.Legacy.Dex.MISSING_TEST_DEX,
                    "Cannot find test dex file in base apk file \"${baseApk.name}\"."
                )
                baseApk.getInputStream(testDexEntry)
                    .use { stream ->
                        output.ensureParentIsExistingDirectory()
                            .outputStream()
                            .buffered()
                            .use(stream::copyTo)
                    }
                if (output.crc32 != testDexEntry.crc) {
                    throw Tinker.Error(
                        Tinker.Error.Deploy.Legacy.Dex.INVALID_DEPLOY_RESULT,
                        "CRC32 checksum \"${output.crc32}\" of test dex file as patch result "
                                + "is not match \"${testDexEntry.crc}\" in base apk file \"${baseApk.name}\".",
                    )
                }
            }
        }
    }
}

private fun dexDeployToApkInternal(
    baseApk: ZipFile,
    diffPackage: ZipFile,
    apk: File
) {
    withTemporaryDirectory { temporaryDirectory ->
        debugLog(TAG) {
            "Creating dex files to \"${temporaryDirectory.absolutePath}\"."
        }
        createDexFiles(baseApk, diffPackage, temporaryDirectory)
        val sorted = traceE("deploy.legacy.dex.search_and_sort") {
            temporaryDirectory.searchAndSortDexFiles()
                ?.map { dexName ->
                    val match = classesDexWithIndexPattern.matchEntire(dexName.name)
                        ?: return@map null to dexName
                    val dexIndex = match.groupValues[1].takeIf { it.isNotEmpty() }?.toInt() ?: 1
                    return@map dexIndex to dexName
                }
                ?: throw Tinker.Error(
                    Tinker.Error.Deploy.Legacy.Dex.NO_DEPLOYED_DEX,
                    "No valid dex file found in directory \"${temporaryDirectory.absolutePath}\"."
                )
        }
        debugLog(TAG) {
            buildList {
                add("Sorted dex files with mapping indexes:")
                sorted.forEach { (index, dex) ->
                    add("  ${dex.absolutePath} -> $index")
                }
            }.joinToString("\n")
        }
        var startIndex = sorted.maxOf { it.first ?: -1 } + 1
        traceS("deploy.legacy.dex.write_apk") {
            apk.ensureParentIsExistingDirectory()
                .outputStream()
                .buffered()
                .let(::AlignedZipOutputStream)
                .use { zip ->
                    sorted.forEach { (index, dex) ->
                        val actualIndex = index ?: startIndex++
                        val name = if (actualIndex == 1) {
                            "classes.dex"
                        } else {
                            "classes$actualIndex.dex"
                        }
                        debugLog(TAG) {
                            "Adding dex file \"${dex.absolutePath}\"" +
                                    " to apk \"${apk.absolutePath}\"" +
                                    " with name \"$name\"."
                        }
                        ZipEntry(name)
                            .apply {
                                method = ZipEntry.STORED
                                size = dex.length()
                                crc = dex.crc32
                            }
                            .let(zip::putNextEntry)
                        dex.inputStream().use { stream ->
                            stream.copyTo(zip)
                        }
                        zip.closeEntry()
                    }
                }
        }
    }
}

internal fun dexDeployToApk(
    baseApk: ZipFile,
    diffPackage: ZipFile,
    apk: File
) {
    debugLog(TAG) {
        "Start deploying dex files of \"${diffPackage.name}\"" +
                " with \"${baseApk.name}\"" +
                " to \"${apk.absolutePath}\"" +
                " via legacy way."
    }
    expected<Tinker.Error.Deploy.Legacy.Dex>("deploy dex files") {
        dexDeployToApkInternal(
            baseApk,
            diffPackage,
            apk,
        )
    }
}